#!/usr/bin/env python3
"""Archive a new plant species from 3D model files.

Usage:
    python3 tools/add_species.py <folder> [--id hibiscus] [--name "HIBISCUS"]

The folder holds .glb files (export from Blender: File > Export > glTF 2.0, format "glTF Binary"):
    plant.glb            required: the mature plant
    leaf.glb             optional: one leaf, shown in the turntable's LEAF mode
    bud.glb, bloom.glb,  optional: a model for that life stage; any stage id from
    seeding.glb, ...     species.js works (vegetative, dormant, rosette ...)

It writes specimens/<id>/models.js (the models, embedded so the app works offline
and from a plain file), creates specimens/<id>/species.js from a template the first
time (edit that file to fill in the record), and adds <id> to specimens/index.js.
Run it again any time you replace a model; your species.js is never overwritten.
"""
import argparse, base64, json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATE = """// Record for {name}. Edit freely; tools/add_species.py never overwrites this file.
EA.addSpecies('{id}', {{
  name: '{name}',                 // up to 10 letters show under the bed
  latin: 'Genus species',
  family: 'Family',
  origin: 'Where it comes from',
  height: 1,                      // size relative to the other plants (1 = about basil height)
  kind: 'annual',                 // 'annual' uses stages; 'perennial' uses seasons (see js/species.js)
  summary: 'A short description of the plant.',
  facts: ['HEIGHT ...', 'LEAVES ...', 'FLOWERS ...'],
  uses: [
    ['CULINARY', '...'],
    ['TRADITIONAL', '...'],
  ],
  history: 'Where the plant has been in human history.',
  leaf: {{ shape: 'oval', len: 0.9, wid: 0.5, serr: 0, note: 'LEAF DESCRIPTION' }}, // used if there is no leaf.glb
  stages: [
    {{ id: 'seed', label: 'SEED', days: 7, g: [0, 0], desc: '...' }},
    {{ id: 'sprout', label: 'SPROUT', days: 10, g: [0.04, 0.12], desc: '...' }},
    {{ id: 'seedling', label: 'SEEDLING', days: 20, g: [0.12, 0.4], desc: '...' }},
    {{ id: 'vegetative', label: 'LEAFY GROWTH', days: 30, g: [0.4, 0.9], desc: '...' }},
    {{ id: 'bud', label: 'BUDDING', days: 8, g: [0.9, 0.95], desc: '...' }},
    {{ id: 'bloom', label: 'IN BLOOM', days: 20, g: [0.95, 1], desc: '...' }},
    {{ id: 'seeding', label: 'SETTING SEED', days: 14, g: [1, 1], desc: '...' }},
    {{ id: 'senescence', label: 'DYING BACK', days: 8, g: [1, 0.7], desc: '...' }},
  ],
  // One entry per bed this species gets. Beds are added to the garden in order.
  beds: [{{ sowDay: 0 }}],
}});
"""

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('folder')
    ap.add_argument('--id', help='short lowercase id (default: folder name)')
    ap.add_argument('--name', help='display name (default: id in capitals)')
    a = ap.parse_args()

    src = pathlib.Path(a.folder)
    sid = re.sub(r'[^a-z0-9_]', '', (a.id or src.name).lower())
    if not sid:
        sys.exit('Give the species a short id, e.g. --id hibiscus')
    files = {p.stem.lower(): p for p in sorted(src.glob('*.glb'))}
    if 'plant' not in files:
        sys.exit(f'{src} needs a plant.glb (found: {", ".join(p.name for p in files.values()) or "no .glb files"})')
    for slot, p in files.items():
        if p.read_bytes()[:4] != b'glTF':
            sys.exit(f'{p.name} is not a binary glTF (.glb) file')

    out = ROOT / 'specimens' / sid
    out.mkdir(parents=True, exist_ok=True)
    slots = {slot: 'data:model/gltf-binary;base64,' + base64.b64encode(p.read_bytes()).decode() for slot, p in files.items()}
    (out / 'models.js').write_text(f"// Generated by tools/add_species.py. Re-run it to update.\nEA.addModels('{sid}', {json.dumps(slots)});\n")

    rec = out / 'species.js'
    created = not rec.exists()
    if created:
        rec.write_text(TEMPLATE.format(id=sid, name=(a.name or sid).upper()[:20]))

    index = ROOT / 'specimens' / 'index.js'
    text = index.read_text()
    ids = json.loads(re.search(r'loadAll\((\[.*?\])\)', text, re.S).group(1))
    if sid not in ids:
        ids.append(sid)
        index.write_text(re.sub(r'loadAll\(\[.*?\]\)', 'loadAll(' + json.dumps(ids) + ')', text, flags=re.S))

    kb = sum(p.stat().st_size for p in files.values()) // 1024
    print(f'Archived {sid}: {", ".join(sorted(files))} ({kb} KB)')
    print(f'  {"Created" if created else "Kept"} {rec.relative_to(ROOT)}' + (' <- fill in the record' if created else ''))
    if kb > 5000:
        print('  Note: big models slow the page. Decimate in Blender to a few thousand faces; it is drawn at Game Boy size anyway.')

if __name__ == '__main__':
    main()
